@localhost = localhost:4004/odata/v4/main
@id = 5751e59a-75ee-469b-b79b-7e89ef5944f3
//@customerID = cd58215d-2bb0-4576-babf-7c25cfff6c2b
@customerID = 23605262-fb2c-4f1b-8625-a0a452c29f14
@productID = 18767552-0f35-4c66-8584-867c96933ed0
@productID2 = 18767551-141b-45b9-9d29-352fd1628709

Get http://{{localhost}}/SalesOrderHeaders
Content-type: application/json

###
// busca apenas 1 registro
Get http://{{localhost}}/SalesOrderHeaders({{id}})?$expand=items($select=price)
Content-type: application/json

###
//criação novo registro
post http://localhost:4004/odata/v4/main/SalesOrderHeaders
Content-type: application/json

{
   "id": "{{id}}",
   "customer_id": "{{customerID}}",
   "totalAmount": 220,
   "items":[
    {
      "id": "bd5f05e1-6dd8-4e0c-ba31-b1e41462bcbe",
      "header_id": "{{id}}",
      "product_id": "{{productID}}",
      "quantity": 1,
      "price": 60
    },
    {
      "id": "9e3bdb96-b9fc-4cb6-b1d1-f076cd32c126",
      "header_id": "{{id}}",
      "product_id": "{{productID2}}",
      "quantity": 2,
      "price": 80
    }
   ]
}

# entity SalesOrderHeaders : managed {
#     key id          : UUID;
#         customer    : Association to Customers;
#         totalAmount : Decimal(15, 2);
#         items       : Composition of SalesOrderItems
#                           on items.header = $self;
# }

# entity SalesOrderItems {
#     key id       : UUID;
#         header   : Association to SalesOrderHeaders;
#         product  : Association to Products;
#         quantity : Integer;
#         price    : Decimal(15, 2);
# }

###

//deleção registro
delete http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-type: application/json